桌面:
  同花顺_桌面: 'match_image/桌面/同花顺_桌面.png'
  同花顺_任务栏: 'match_image/桌面/同花顺_任务栏.png'
首页:
  页面放大: 'match_image/首页/页面放大.png'
  收起推荐: 'match_image/首页/收起推荐.png'
  自选: 'match_image/首页/自选.png'
  下翻: 'match_image/首页/下翻.png'
自选:
  我的板块: 'match_image/自选/我的板块.png'
  监测: 'match_image/自选/监测.png'
  分时图: 'match_image/自选/分时图.png'
  添加股票: 'match_image/自选/添加股票.png'
  操作: 'match_image/自选/操作.png'
  搜索框: 'match_image/自选/搜索框.png'
  图片识别导入: 'match_image/自选/图片识别导入.png'
  加股票: 'match_image/自选/加股票.png'
  关闭添加: 'match_image/自选/关闭添加.png'
信息:
  下一个股: 'match_image/信息/下一个股.png'
  公司亮点: 'match_image/信息/公司亮点.png'
  主营业务: 'match_image/信息/主营业务.png'
  收入: 'match_image/信息/收入.png'
  净利润: 'match_image/信息/净利润.png'
  毛利率: 'match_image/信息/毛利率.png'
微信:
  微信_任务栏: 'match_image/微信/微信_任务栏.png'
  监测: 'match_image/微信/监测.png'
regex:
  名称: '[\u4e00-\u9fa5]+'
  名称和代码: '([\u4e00-\u9fa5]+).*?(\d{6})'
  macdfs: 'MACDFS:\s*([+-]\d\.\d{3})'
