匹配图片:
  同花顺_桌面: 'match_image/同花顺_桌面.png'
  同花顺_任务栏: 'match_image/同花顺_任务栏.png'
  页面放大: 'match_image/页面放大.png'
  自选: 'match_image/自选.png'
  自选_涨幅: 'match_image/自选_涨幅.png'
  # 股票
  上证指数: 'match_image/上证指数.png'
  微盘股: 'match_image/微盘股.png'
  国债指数: 'match_image/国债指数.png'
  证券: 'match_image/证券.png'